Repository spacetelescope/tweakwcs, pull requests merged in 2019-04, with the labels that each got.

#74 Add azure badge to README.rst
  README.rst
Labels: no changelog entry needed

#75 Rename wcsutil.planar_rot_3D to planar_rot_3d (PEP8)
  CHANGELOG.rst
  tweakwcs/wcsimage.py
  tweakwcs/wcsutils.py
Labels: code cleanup

#76 Add wcsutils tests
  tweakwcs/tests/test_nop.py
  tweakwcs/tests/test_wcsutils.py
Labels: no changelog entry needed, tests

#78 Additional linearfit.py unit tests
  tweakwcs/tests/test_linearfit.py
Labels: no changelog entry needed, tests

#79 Azure: Add codecov
  azure-templates.yml
  setup.py
Labels: no changelog entry needed, tests

#80 Azure codecov2
  .coveragerc
  .gitignore
  azure-templates.yml
Labels: no changelog entry needed, tests

#81 Add codecov badge
  README.rst
Labels: no changelog entry needed

#83 Azure: Show pip freeze output
  azure-templates.yml
Labels: no changelog entry needed, tests

#82 Add unit tests for TPWCS and derived classes and related modules
  CHANGELOG.rst
  tweakwcs/__init__.py
  tweakwcs/imalign.py
  tweakwcs/linalg.py
  tweakwcs/linearfit.py
  tweakwcs/matchutils.py
  tweakwcs/tests/helper_tpwcs.py
  tweakwcs/tests/test_jwst_utils.py
  tweakwcs/tests/test_matchutils.py
  tweakwcs/tests/test_tpwcs.py
  tweakwcs/utils/jwst_utils.py
Labels: code cleanup, no changelog entry needed, tests

#84 Bug fixes and (almost) complete test coverage
  CHANGELOG.rst
  setup.cfg
  tweakwcs/imalign.py
  tweakwcs/linalg.py
  tweakwcs/linearfit.py
  tweakwcs/matchutils.py
  tweakwcs/tests/conftest.py
  tweakwcs/tests/test_imalign.py
  tweakwcs/tests/test_jwst_utils.py
  tweakwcs/tests/test_tpwcs.py
  tweakwcs/tests/test_wcsimage.py
  tweakwcs/tpwcs.py
  tweakwcs/utils/jwst_utils.py
  tweakwcs/wcsimage.py
Labels: bug, code cleanup, tests

#85 change indexing in model parameters
  tweakwcs/tests/helper_tpwcs.py
  tweakwcs/tests/test_tpwcs.py
Labels: enhancement

#86 Code cleanup
  tweakwcs/imalign.py
  tweakwcs/linalg.py
  tweakwcs/matchutils.py
  tweakwcs/tests/helper_tpwcs.py
  tweakwcs/tpwcs.py
  tweakwcs/wcsimage.py
Labels: code cleanup, no changelog entry needed

#87 Bump version for release
  CHANGELOG.rst
  setup.cfg
Labels: code cleanup, no changelog entry needed

#88 Azure: Require jwst package (master)
  azure-templates.yml
Labels: no changelog entry needed, tests
