Repository spacetelescope/tweakwcs, pull requests merged in 2019-03, with the labels that each got.

#61 Fix setuptools
  pyproject.toml
  setup.py
Labels: bug

#63 Clean up C code
  setup.cfg
  src/carrutils.c
Labels: code cleanup, no changelog entry needed

#64 C code cleanup: consistent indentation
  src/carrutils.c
Labels: code cleanup

#67 Fix incorrect pointer type
  CHANGELOG.rst
  setup.cfg
  src/carrutils.c
Labels: bug

#69 Improve 2D-histogram intitial shift estimation algorithm
  CHANGELOG.rst
  setup.cfg
  setup.py
  src/carrutils.c
  tweakwcs/matchutils.py
Labels: bug

#70 setup.py: Remove imports
  setup.py
Labels: code cleanup

#71 PEP8 and other cosmetic changes; sphinx
  CHANGELOG.rst
  docs/source/groupwcs.rst
  docs/source/index.rst
  tweakwcs/__init__.py
  tweakwcs/imalign.py
  tweakwcs/linalg.py
  tweakwcs/linearfit.py
  tweakwcs/matchutils.py
  tweakwcs/tpwcs.py
  tweakwcs/utils/__init__.py
  tweakwcs/utils/jwst_utils.py
  tweakwcs/wcsimage.py
  tweakwcs/wcsutils.py
Labels: code cleanup, documentation

#72 Azure pipelines
  azure-pipelines.yml
  azure-templates.yml
  setup.cfg
  setup.py
  tweakwcs/tests/__init__.py
  tweakwcs/tests/test_nop.py
Labels: code cleanup, enhancement, no changelog entry needed
