Repository spacetelescope/tweakwcs, pull requests merged in 2022-06, with the labels that each got.

#160 Fix RTD formatting
  .readthedocs.yml
  docs/rtd-pip-requirements.txt
  docs/source/conf.py
Labels: documentation, no changelog entry needed

#161 Fix RTD formatting
  .readthedocs.yml
  docs/rtd-pip-requirements.txt
  docs/source/conf.py
  setup.py
Labels: documentation, no changelog entry needed

#162 Fix RTD Formatting. Another attempt.
  docs/_static/stsci_logo_large.png
  docs/_static/stsci_logo_small.png
  docs/rtd-pip-requirements.txt
  docs/source/conf.py
Labels: documentation, no changelog entry needed

#163 Update RTD config to use new build specification
  .readthedocs.yml
Labels: documentation, Maintenance

#164 Fix css path in sphinx config
  docs/source/conf.py
Labels: bug, documentation

#165 Simplify custom css and move conf.py to the root of docs
  .readthedocs.yml
  docs/Makefile
  docs/_static/css/custom-tweakwcs.css
  docs/_static/css/custom.css
  docs/conf.py
  docs/index.rst
  tweakwcs/imalign.py
  tweakwcs/linalg.py
  tweakwcs/linearfit.py
  tweakwcs/matchutils.py
  tweakwcs/tpwcs.py
  tweakwcs/wcsimage.py
  tweakwcs/wcsutils.py
Labels: documentation, no changelog entry needed

#166 Use STScI RTD theme
  docs/_static/stsci_logo_large.png
  docs/_static/stsci_logo_small.png
  docs/conf.py
  docs/rtd-pip-requirements.txt
  setup.py
Labels: documentation, code cleanup, no changelog entry needed
