Repository spacetelescope/tweakwcs, pull requests merged in 2024-01, with the labels that each got.

#195 Improve how reference catalog is expanded
  CHANGELOG.rst
  tweakwcs/imalign.py
Labels: bug

#196 Use KDTree to reduce memory & compute in _xy_2dhist
  CHANGELOG.rst
  tweakwcs/matchutils.py
Labels: enhancement

#197 Update change log for release 0.8.6
  CHANGELOG.rst
Labels: no changelog entry needed, Maintenance
